# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"5\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\"\n\x10RegisterResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1f\n\rLoginResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\"\n\x0eGetUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"6\n\x0fGetUserResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tis_active\x18\x02 \x01(\x08\x32\x94\x01\n\x0b\x41uthService\x12/\n\x08Register\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12,\n\x07GetUser\x12\x0f.GetUserRequest\x1a\x10.GetUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=14
  _globals['_REGISTERREQUEST']._serialized_end=67
  _globals['_REGISTERRESPONSE']._serialized_start=69
  _globals['_REGISTERRESPONSE']._serialized_end=103
  _globals['_LOGINREQUEST']._serialized_start=105
  _globals['_LOGINREQUEST']._serialized_end=155
  _globals['_LOGINRESPONSE']._serialized_start=157
  _globals['_LOGINRESPONSE']._serialized_end=188
  _globals['_GETUSERREQUEST']._serialized_start=190
  _globals['_GETUSERREQUEST']._serialized_end=224
  _globals['_GETUSERRESPONSE']._serialized_start=226
  _globals['_GETUSERRESPONSE']._serialized_end=280
  _globals['_AUTHSERVICE']._serialized_start=283
  _globals['_AUTHSERVICE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
