# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\"V\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\x05\"c\n\x11\x43reatePostRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\x05\")\n\x12\x43reatePostResponse\x12\x13\n\x04post\x18\x01 \x01(\x0b\x32\x05.Post\"\x1d\n\x0fReadPostRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\'\n\x10ReadPostResponse\x12\x13\n\x04post\x18\x01 \x01(\x0b\x32\x05.Post\"\"\n\x0fGetPostsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"(\n\x10GetPostsResponse\x12\x14\n\x05posts\x18\x01 \x03(\x0b\x32\x05.Post\"T\n\x08UserInfo\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x14\n\x05posts\x18\x04 \x03(\x0b\x32\x05.Post\"$\n\x11GetProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"4\n\x12GetProfileResponse\x12\x1e\n\x0binformation\x18\x01 \x01(\x0b\x32\t.UserInfo2\xa6\x01\n\x0bPostService\x12\x35\n\nCreatePost\x12\x12.CreatePostRequest\x1a\x13.CreatePostResponse\x12/\n\x08ReadPost\x12\x10.ReadPostRequest\x1a\x11.ReadPostResponse\x12/\n\x08GetPosts\x12\x10.GetPostsRequest\x1a\x11.GetPostsResponse2G\n\x0eProfileService\x12\x35\n\nGetProfile\x12\x12.GetProfileRequest\x1a\x13.GetProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POST']._serialized_start=14
  _globals['_POST']._serialized_end=100
  _globals['_CREATEPOSTREQUEST']._serialized_start=102
  _globals['_CREATEPOSTREQUEST']._serialized_end=201
  _globals['_CREATEPOSTRESPONSE']._serialized_start=203
  _globals['_CREATEPOSTRESPONSE']._serialized_end=244
  _globals['_READPOSTREQUEST']._serialized_start=246
  _globals['_READPOSTREQUEST']._serialized_end=275
  _globals['_READPOSTRESPONSE']._serialized_start=277
  _globals['_READPOSTRESPONSE']._serialized_end=316
  _globals['_GETPOSTSREQUEST']._serialized_start=318
  _globals['_GETPOSTSREQUEST']._serialized_end=352
  _globals['_GETPOSTSRESPONSE']._serialized_start=354
  _globals['_GETPOSTSRESPONSE']._serialized_end=394
  _globals['_USERINFO']._serialized_start=396
  _globals['_USERINFO']._serialized_end=480
  _globals['_GETPROFILEREQUEST']._serialized_start=482
  _globals['_GETPROFILEREQUEST']._serialized_end=518
  _globals['_GETPROFILERESPONSE']._serialized_start=520
  _globals['_GETPROFILERESPONSE']._serialized_end=572
  _globals['_POSTSERVICE']._serialized_start=575
  _globals['_POSTSERVICE']._serialized_end=741
  _globals['_PROFILESERVICE']._serialized_start=743
  _globals['_PROFILESERVICE']._serialized_end=814
# @@protoc_insertion_point(module_scope)
